<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>GalaxyPPG.Server</RootNamespace>
    <AssemblyName>GalaxyPPG.Server</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GalaxyPPG.Common\GalaxyPPG.Common.csproj" />
  </ItemGroup>

</Project>
