<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>GalaxyPPG.Common</RootNamespace>
    <AssemblyName>GalaxyPPG.Common</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>

</Project>
